import React, { useState } from 'react';
import { View, StyleSheet, Alert, TouchableOpacity } from 'react-native';
import { ThemedView, ThemedText, ThemedButton, ThemedInput, useThemeColors } from '../components/ThemedComponents';
import { useAuth } from '../context/AuthContext';
import { spacing, colors } from '../theme';
import { generateMasterPassword } from '../utils/crypto';
import * as Clipboard from 'expo-clipboard';
import { Ionicons } from '@expo/vector-icons';

export default function LoginScreen() {
    const { login, register, usersList } = useAuth();
    const themeColors = useThemeColors();

    // UI States
    const [mode, setMode] = useState(usersList.length === 0 ? 'register' : 'login'); // 'login' or 'register'
    const [username, setUsername] = useState(usersList.length > 0 ? usersList[0] : '');
    const [password, setPassword] = useState('');
    const [loading, setLoading] = useState(false);
    const [generatedPassword, setGeneratedPassword] = useState('');

    const handleAction = async () => {
        if (!username) {
            Alert.alert('Erreur', 'Veuillez renseigner un nom d\'utilisateur');
            return;
        }

        if (mode === 'register') {
            // REGISTER FLOW
            // Check if user already exists
            if (usersList.length > 0) {
                Alert.alert(
                    'Attention',
                    'Créer un nouveau compte supprimera DÉFINITIVEMENT le compte existant et toutes ses données.\n\nVoulez-vous vraiment continuer ?',
                    [
                        { text: 'Annuler', style: 'cancel' },
                        {
                            text: 'Supprimer et Créer',
                            style: 'destructive',
                            onPress: async () => {
                                await proceedRegistration(true);
                            }
                        }
                    ]
                );
                return;
            }

            await proceedRegistration();
        } else {
            // LOGIN FLOW
            if (!password) {
                Alert.alert('Erreur', 'Mot de passe requis');
                return;
            }
            setLoading(true);
            try {
                const success = await login(username, password);
                if (!success) Alert.alert('Erreur', 'Identifiants incorrects');
            } finally {
                setLoading(false);
            }
        }
    };

    const proceedRegistration = async (forceReset = false) => {
        setLoading(true);
        try {
            // If user didn't type a password, we generate one (optional convention)
            // But typically for "Master Password" user wants to choose it or see it.
            // Existing logic generated one if "isFirstLaunch".
            // Let's keep the logic: if password is empty, generate and register.
            let pwdToUse = password;
            let autoGenerated = false;

            if (!pwdToUse) {
                pwdToUse = generateMasterPassword();
                autoGenerated = true;
            }

            const result = await register(username, pwdToUse, forceReset);
            if (!result.success) {
                Alert.alert('Erreur', 'Ce nom d\'utilisateur existe déjà ou erreur technique.');
            } else {
                // Show Recovery Key
                Alert.alert(
                    'Compte Créé',
                    `Voici votre CLÉ DE RÉCUPÉRATION.\nCopiez-la en lieu sûr. Elle permet de déchiffrer vos données sans mot de passe.\n\n${result.key}`,
                    [
                        {
                            text: 'Copier',
                            onPress: async () => {
                                await Clipboard.setStringAsync(result.key);
                                Alert.alert('Copié !');
                            }
                        },
                        { text: 'OK' }
                    ]
                );

                if (autoGenerated) {
                    setGeneratedPassword(pwdToUse);
                }
            }
        } finally {
            setLoading(false);
        }
    };

    return (
        <ThemedView style={styles.container}>
            <View style={styles.content}>
                <ThemedText type="header" style={styles.title}>
                    VaultX
                </ThemedText>

                {/* User Tabs if users exist */}
                {usersList.length > 0 && (
                    <View style={{ flexDirection: 'row', justifyContent: 'center', marginBottom: spacing.l }}>
                        <TouchableOpacity
                            onPress={() => { setMode('login'); setUsername(usersList[0] || ''); }}
                            style={{
                                padding: spacing.s,
                                borderBottomWidth: 2,
                                borderBottomColor: mode === 'login' ? themeColors.primary : 'transparent'
                            }}
                        >
                            <ThemedText style={{ fontWeight: mode === 'login' ? 'bold' : 'normal' }}>Connexion</ThemedText>
                        </TouchableOpacity>
                        <View style={{ width: spacing.m }} />
                        <TouchableOpacity
                            onPress={() => { setMode('register'); setUsername(''); setPassword(''); }}
                            style={{
                                padding: spacing.s,
                                borderBottomWidth: 2,
                                borderBottomColor: mode === 'register' ? themeColors.primary : 'transparent'
                            }}
                        >
                            <ThemedText style={{ fontWeight: mode === 'register' ? 'bold' : 'normal' }}>Nouveau Profil</ThemedText>
                        </TouchableOpacity>
                    </View>
                )}

                <ThemedText style={styles.subtitle}>
                    {mode === 'register' ? 'Créer un nouveau profil sécurisé' : 'Accéder à votre coffre'}
                </ThemedText>

                {/* Username Input or Selection */}
                {mode === 'login' && usersList.length > 0 ? (
                    <View style={{ marginBottom: spacing.m }}>
                        <ThemedText style={{ marginBottom: spacing.s, color: themeColors.textSecondary }}>Utilisateur</ThemedText>
                        <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: spacing.s }}>
                            {usersList.map(u => (
                                <TouchableOpacity
                                    key={u}
                                    onPress={() => setUsername(u)}
                                    style={{
                                        paddingVertical: 8,
                                        paddingHorizontal: 16,
                                        borderRadius: 20,
                                        backgroundColor: username === u ? themeColors.primary : themeColors.card,
                                        borderWidth: 1,
                                        borderColor: themeColors.border
                                    }}
                                >
                                    <ThemedText style={{ color: username === u ? themeColors.primaryText : themeColors.text }}>{u}</ThemedText>
                                </TouchableOpacity>
                            ))}
                        </View>
                    </View>
                ) : (
                    <ThemedInput
                        label="Nom d'utilisateur"
                        value={username}
                        onChangeText={setUsername}
                        autoCapitalize="none"
                        placeholder="Ex: alice"
                    />
                )}

                <ThemedInput
                    label={mode === 'register' && !password ? "Mot de passe (Laisser vide pour générer)" : "Mot de passe"}
                    value={password}
                    onChangeText={setPassword}
                    secureTextEntry
                />

                <ThemedButton
                    title={mode === 'register' ? 'Créer le Profil' : 'Déverrouiller'}
                    onPress={handleAction}
                    loading={loading}
                    style={styles.button}
                />

                {mode === 'register' && generatedPassword ? (
                    <View style={styles.generatedContainer}>
                        <ThemedText style={[styles.generatedInfo, { color: colors.textSecondary }]}>
                            Dernier mot de passe généré :
                        </ThemedText>
                        <ThemedText style={styles.generatedPassword}>
                            {generatedPassword}
                        </ThemedText>
                        <ThemedButton
                            title="Copier"
                            variant="secondary"
                            onPress={async () => {
                                await Clipboard.setStringAsync(generatedPassword);
                                Alert.alert('Copié');
                            }}
                            style={styles.copyButton}
                        />
                    </View>
                ) : null}
            </View>
        </ThemedView>
    );
}

const styles = StyleSheet.create({
    container: {
        justifyContent: 'center',
        padding: spacing.l,
        flex: 1,
    },
    content: {
        width: '100%',
        maxWidth: 400,
        alignSelf: 'center',
    },
    title: {
        fontSize: 40,
        textAlign: 'center',
        marginBottom: spacing.s,
    },
    subtitle: {
        textAlign: 'center',
        marginBottom: spacing.xl,
        color: colors.textSecondary,
    },
    button: {
        marginTop: spacing.m,
    },
    generatedContainer: {
        marginTop: spacing.l,
        alignItems: 'center',
        padding: spacing.m,
        backgroundColor: 'rgba(0,0,0,0.05)',
        borderRadius: 8
    },
    generatedInfo: {
        fontStyle: 'italic',
        textAlign: 'center',
        marginBottom: spacing.s,
    },
    generatedPassword: {
        fontSize: 16,
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: spacing.s,
    },
    copyButton: {
        alignSelf: 'center',
    },
});
